[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd backend-node && npm ci"]

[phases.build]
cmds = ["cd backend-node && npm run build", "cd backend-node && npx prisma generate"]

[start]
cmd = "cd backend-node && npm start"
